# Generated by Django 6.0.2 on 2026-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
